apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Your Beautiful Landing Page</title>
        <style>
            body {
                font-family: 'Arial', sans-serif;
                margin: 0;
                padding: 0;
                box-sizing: border-box;
                background-color: #f4f4f4;
                color: #333;
                overflow-x: hidden; /* Prevent horizontal scrollbars on small screens */
            }

            header {
                background-color: #3498db;
                color: #fff;
                text-align: center;
                padding: 1em;
                animation: fadeIn 1s ease-in-out; /* Add fade-in animation */
            }

            @keyframes fadeIn {
                from { opacity: 0; }
                to { opacity: 1; }
            }

            section {
                text-align: center;
                padding: 2em;
            }

            h1 {
                font-size: 2.5em;
                margin-bottom: 20px;
                color: #2c3e50;
            }

            p {
                font-size: 1.2em;
                color: #555;
            }

            .cta-button {
                display: inline-block;
                padding: 10px 20px;
                font-size: 1.2em;
                text-decoration: none;
                color: #fff;
                background-color: #e74c3c;
                border-radius: 5px;
                transition: background-color 0.3s ease;
            }

            .cta-button:hover {
                background-color: #c0392b;
            }

            /* Add parallax effect to the background image */
            body:before {
                content: "";
                display: block;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                z-index: -1;
                background: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeTZqDtQ8k9jwtPh8beFLWZuR6AgX6eURJppvolQbHjw&s') center/cover no-repeat fixed;
                opacity: 0.3;
            }

            footer {
                background-color: #2c3e50;
                color: #fff;
                text-align: center;
                padding: 1em;
                position: fixed;
                bottom: 0;
                width: 100%;
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Your Landing Page</h1>
            <p>Welcome to the most amazing website ever!</p>
        </header>

        <section>
            <h2>Discover a World of Wonders</h2>
            <p>Explore our incredible features and experience something extraordinary.</p>
            <a href="#cta" class="cta-button">Get Started</a>
        </section>

        <footer>
            &copy; 2023 Your Company Name
        </footer>
    </body>
    </html>

