apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Custom Nginx Page</title>
    </head>
    <body>
      <h1>Hello, Kubernetes!</h1>
    </body>
    </html>
