apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to nginx bank!</title>
    </head>
    <body>
        <h1>Hello, World! bank bank</h1>
    </body>
    </html>
