esphome:
  name: bed-room-controller
  friendly_name: bed-room-controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "please_use_auto_generate_or_your_own"

ota:
  password: "yyyyy"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed-Room-Controller"
    password: "please_use_auto_generate_or_your_own"

captive_portal:

output:
  - platform: gpio
    id: "light1"
    pin: 5
light:
  - platform: binary
    output: "light1"
    name: "My light"
sensor:
  - platform: dht
    pin: 22
    temperature:
      name: "Bed Room Temperature"
    humidity:
      name: "Bed Room Humidity"
    update_interval: 60s    