esphome:
  name: bed-room-controller
  friendly_name: bed-room-controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "d62Y+ks1lwiN8xoBAQ8s1P+b0DhMncqPWHX+3DixC1E="

ota:
  password: "d2bba8c0bca30dc8217d2677ec06bf21"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed-Room-Controller"
    password: "oN3X6iZyYRqn"

captive_portal:

output:
  - platform: gpio
    id: "light1"
    pin: 5
light:
  - platform: binary
    output: "light1"
    name: "My light"
sensor:
  - platform: dht
    pin: 22
    temperature:
      name: "Bed Room Temperature"
    humidity:
      name: "Bed Room Humidity"
    update_interval: 60s    