version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./ha-config:/config
    restart: unless-stopped
    environment:
      TZ: Asia/Bangkok
    ports:
      - 8123:8123
  esphome:
    image: ghcr.io/esphome/esphome
    restart: unless-stopped
    volumes:
      - ./esphome-config:/config:rw
    environment:
      TZ: Asia/Bangkok
    ports:
      - 6052:6052