# Just for test run not email
# docker compose up snipe-it 
# copy APP_KEY to compose file
# docker compose up -d mysql 
# docker compose up -d snipe-it 
version: "2.1"
services:
  snipe-it:
    image: snipe/snipe-it
    container_name: snipe-it
    environment:
      - APP_DEBUG=false
      - APP_KEY=YourKey
      - APP_TIMEZONE=Asia/Bangkok
      - APP_LOCALE=en
      - APP_URL=http://192.168.2.100:8080
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      # - MYSQL_PORT_3306_TCP_PORT=
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=snipeit
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
  mysql:
    image: mysql:5.6
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - sniteit_mysql_data:/var/lib/mysql
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: snipeit
      MYSQL_DATABASE: snipeit
      MYSQL_USER: snipeit
      MYSQL_PASSWORD: snipeit
volumes:
  sniteit_mysql_data:
